### ISSUE TITLE
Possible bug: if second category is unchecked the first one also after reload is uncheked

### ISSUE THREAD

**Issue by 01Kuzma** [TecArt/grav-plugin-tecart-cookie-manager#11]
Hi!
It seems, that I've observed a minor bug.
For example, I've created two scripts belonging to two separate categories.
Let's assume that the first category is mandatory cookies. So, in `scripts` settings we check the `opt-in (show checkbox on banner) ` to `no` and set `Default (script included or not) ` to `active`.
Then let's load the page, the `mandatory` scripts are loaded and in settings, the checkbox is set to true:
![image](https://user-images.githubusercontent.com/569504/190698337-9b3eec7a-d6e8-4b79-8cbd-fec2f89c8c8c.png)
but with `null` label, it's also a small bug.
Then accept all cookies. Now the `mandatory`  (default category which always will be set to true) and the second category are set to `true`. Now go to settings, choose the second category and uncheck the switch.
The `mandatory` category will be also unchecked, while it should be set to `true`
And during the debug process it could be vice versa - a mandatory cookie is set to `allowed":true` in storage, but in settings the first category is unset and the second selected...

**Comment by ChristianaHoJo** [comment]
Hi @01Kuzma,

null is shown because label text is empty. We now set blueprint field for script text to validation required.

I could reproduce that the active script with the disabled toggler was removed when uncheck the category. I fixed this bug.
https://github.com/TecArt/grav-plugin-tecart-cookie-manager/pull/14

But I could not reproduce the fact that one category setting changes another category setting. Maybe you can see any JavaScript errors in your developer console?

Greetings and thank you for your feedback.
Christiana
