### ISSUE TITLE
Need exact tutorial how to add this "cookie banner" button

### ISSUE THREAD

**Issue by Staubgeborener** [TecArt/grav-plugin-tecart-cookie-manager#16]
[Here ](https://github.com/TecArt/grav-plugin-tecart-cookie-manager#add-link-to-settings-in-theme) is addressed very short how to set the button manually.

But how and where exactly do i need to add this code? Let's say i create a new page in grav cms called "test". There is can add some code and text. If i try something like

```html
<html>

<script>
// open tecart cookie banner settings modal by click on link
$('.tcb-settings-link').on('click', function (e) {
    e.preventDefault();
    if($('.tcb-settings-modal').length > 0) {
        if ($('.tcb-settings-modal').css('display') == 'none') {
            $('.tcb-settings-modal').show();
        }
    }
});
</script>

<body>
{% if config.plugins["tecart-cookie-manager"].enabled %}
<li class="list-inline-item u-list__item">
    <a href="#" class="u-list__link text-secondary tcb-settings-link">Cookie Banner</a>
</li>
{% endif %}
</body>

</html>
```

All i get in the browser on the site "test" is this

```
{% if config.plugins["tecart-cookie-manager"].enabled %}
[Cookie Banner](https://mydomain.com/test#)
{% endif %}
```

So how does this button work **exactly**?

**Comment by ChristianaHoJo** [comment]
Hello @Staubgeborener ,

it seems like you're writing the code in the text editor for page content. This editor seems to alter the syntax of the entered link / code by converting it into Markdown, which is causing the issue. You need to ensure that the code appears correctly in the page source code.

So far, we've always directly integrated the plugin code into the page template (html/twig) since the link usually needs to appear on all pages, such as in the footer. Why not try placing the code directly in your theme template?

Best regards,
Christiana
